# Generated by Django 3.0.5 on 2020-05-08 22:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, max_length=64, null=True)),
                ('instruction', models.CharField(blank=True, max_length=64, null=True)),
                ('final_page', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'типы вопросов',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ManyToManyField(to='maker_app.Company')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker_app.Page')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, unique=True)),
                ('head_of_department', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True)),
                ('workers', models.PositiveIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ManyToManyField(to='maker_app.Company')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maker_app.Structure')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=128)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker_app.QuestionType')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker_app.Question'),
        ),
    ]
