# Generated by Django 3.0.5 on 2020-05-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_1', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64)),
                ('workers', models.PositiveIntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor_app.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor_app.QuestionType1'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('workers', models.PositiveIntegerField(max_length=16)),
                ('code', models.PositiveIntegerField(max_length=16)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor_app.Structure')),
                ('surveys', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor_app.Survey')),
            ],
        ),
    ]
