# Generated by Django 3.0.5 on 2020-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='workers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='workers',
            field=models.PositiveIntegerField(),
        ),
    ]
