# Generated by Django 3.0.5 on 2020-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0002_auto_20200502_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
        migrations.AddField(
            model_name='structure',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='workers',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
