# Generated by Django 3.0.5 on 2020-05-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0004_auto_20200503_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='departments',
            new_name='department',
        ),
    ]
