# Generated by Django 3.0.5 on 2020-05-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0006_auto_20200503_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Structure'),
        ),
        migrations.AlterField(
            model_name='company',
            name='surveys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.QuestionType1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Question'),
        ),
    ]
