# Generated by Django 3.0.5 on 2020-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0007_auto_20200503_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionType1',
            new_name='QuestionType',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type_1',
            new_name='question_type',
        ),
        migrations.RenameField(
            model_name='questiontype',
            old_name='type_1',
            new_name='question_type_name',
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
