# Generated by Django 3.0.5 on 2020-05-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0008_auto_20200503_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='constructor_app.Question'),
        ),
    ]
