# Generated by Django 3.0.5 on 2020-05-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0010_auto_20200503_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Structure'),
        ),
    ]
