# Generated by Django 3.0.5 on 2020-05-03 22:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0011_auto_20200503_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='code',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='workers',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='constructor_app.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
