# Generated by Django 3.0.5 on 2020-05-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0012_auto_20200503_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='constructor_app.Structure'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
