# Generated by Django 3.0.5 on 2020-05-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0013_auto_20200503_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='parent',
        ),
        migrations.AddField(
            model_name='structure',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='constructor_app.Structure'),
        ),
    ]
