# Generated by Django 3.0.5 on 2020-05-03 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0015_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor_app.Genre'),
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
