# Generated by Django 3.0.5 on 2020-05-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0016_auto_20200503_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Structure',
        ),
    ]
