# Generated by Django 3.0.5 on 2020-05-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0017_auto_20200504_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='name',
            new_name='department',
        ),
    ]
