# Generated by Django 3.0.5 on 2020-05-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0018_auto_20200504_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='head_of_department',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
