# Generated by Django 3.0.5 on 2020-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0020_auto_20200504_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='workers',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
