# Generated by Django 3.0.5 on 2020-05-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0021_auto_20200504_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='code',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='workers',
        ),
    ]
