# Generated by Django 3.0.5 on 2020-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0022_auto_20200504_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
