# Generated by Django 3.0.5 on 2020-05-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0024_auto_20200504_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company'),
        ),
    ]
