# Generated by Django 3.0.5 on 2020-05-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0025_auto_20200504_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('company', models.ManyToManyField(to='constructor_app.Company')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor_app.UserCategory')),
            ],
        ),
    ]
