# Generated by Django 3.0.5 on 2020-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_app', '0027_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='company',
            name='surveys',
        ),
        migrations.AddField(
            model_name='structure',
            name='company',
            field=models.ManyToManyField(to='constructor_app.Company'),
        ),
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ManyToManyField(to='constructor_app.Company'),
        ),
    ]
